DROP DATABASE IF EXISTS vsa_pr1;
CREATE DATABASE vsa_pr1;
GRANT ALL PRIVILEGES ON DATABASE vsa_pr1 TO vsa;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO vsa;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO vsa;
